# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 19:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userR', models.CharField(blank=True, max_length=50)),
                ('mensaje', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('userE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
