# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0002_partida_condiciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='t1f',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='t1l',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='t2f',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='t2l',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='t3f',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='partida',
            name='t3l',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='partida',
            name='thumb',
            field=models.ImageField(default='pic_folder/bingo.png', upload_to='salas/logos/'),
        ),
    ]
