# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-10 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0004_partida_lineasenjuego'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugada',
            name='premio',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
