# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partidas', '0007_auto_20180307_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='cartonBlank',
            field=models.CharField(default='NO', max_length=2),
        ),
    ]
