# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partida', models.FileField(null=True, upload_to='cargas/excel/')),
                ('asignaciones', models.FileField(null=True, upload_to='cargas/excel/')),
                ('tipopartida', models.CharField(choices=[('MANUAL', 'MANUAL'), ('AUTOMATICO', 'AUTOMATICO')], default='MANUAL', max_length=12)),
                ('tiempoMaster', models.CharField(blank=True, max_length=5)),
                ('tiempoInter', models.CharField(blank=True, max_length=5)),
                ('theme', models.CharField(choices=[('DARK', 'DARK'), ('LIGHT', 'LIGHT')], default='DARK', max_length=12)),
            ],
        ),
    ]
