# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0003_sala_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('apellido', models.CharField(blank=True, max_length=150)),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('thumb', models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/')),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Sala')),
            ],
        ),
    ]
