# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-27 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salas', '0003_sala_created_at'),
        ('partidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlat_ini', models.IntegerField()),
                ('correlat_fin', models.IntegerField()),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.Partida')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salas.Sala')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_1', models.CharField(blank=True, max_length=2)),
                ('l1_2', models.CharField(blank=True, max_length=2)),
                ('l1_3', models.CharField(blank=True, max_length=2)),
                ('l1_4', models.CharField(blank=True, max_length=2)),
                ('l1_5', models.CharField(blank=True, max_length=2)),
                ('l1_6', models.CharField(blank=True, max_length=2)),
                ('l1_7', models.CharField(blank=True, max_length=2)),
                ('l1_8', models.CharField(blank=True, max_length=2)),
                ('l1_9', models.CharField(blank=True, max_length=2)),
                ('l2_1', models.CharField(blank=True, max_length=2)),
                ('l2_2', models.CharField(blank=True, max_length=2)),
                ('l2_3', models.CharField(blank=True, max_length=2)),
                ('l2_4', models.CharField(blank=True, max_length=2)),
                ('l2_5', models.CharField(blank=True, max_length=2)),
                ('l2_6', models.CharField(blank=True, max_length=2)),
                ('l2_7', models.CharField(blank=True, max_length=2)),
                ('l2_8', models.CharField(blank=True, max_length=2)),
                ('l2_9', models.CharField(blank=True, max_length=2)),
                ('l3_1', models.CharField(blank=True, max_length=2)),
                ('l3_2', models.CharField(blank=True, max_length=2)),
                ('l3_3', models.CharField(blank=True, max_length=2)),
                ('l3_4', models.CharField(blank=True, max_length=2)),
                ('l3_5', models.CharField(blank=True, max_length=2)),
                ('l3_6', models.CharField(blank=True, max_length=2)),
                ('l3_7', models.CharField(blank=True, max_length=2)),
                ('l3_8', models.CharField(blank=True, max_length=2)),
                ('l3_9', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Impresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganador_1', models.BooleanField(default=False)),
                ('posible_1', models.BooleanField(default=False)),
                ('ganador_2', models.BooleanField(default=False)),
                ('posible_2', models.BooleanField(default=False)),
                ('ganador_3', models.BooleanField(default=False)),
                ('posible_3', models.BooleanField(default=False)),
                ('ganador_4', models.BooleanField(default=False)),
                ('posible_4', models.BooleanField(default=False)),
                ('ganador_5', models.BooleanField(default=False)),
                ('posible_5', models.BooleanField(default=False)),
                ('ganador_6', models.BooleanField(default=False)),
                ('posible_6', models.BooleanField(default=False)),
                ('ganador_7', models.BooleanField(default=False)),
                ('posible_7', models.BooleanField(default=False)),
                ('ganador_8', models.BooleanField(default=False)),
                ('posible_8', models.BooleanField(default=False)),
                ('linea', models.IntegerField(default=0)),
                ('ganador_9', models.BooleanField(default=False)),
                ('posible_9', models.BooleanField(default=False)),
                ('ganador_10', models.BooleanField(default=False)),
                ('posible_10', models.BooleanField(default=False)),
                ('ganador', models.BooleanField(default=False)),
                ('ganador_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(editable=False, null=True)),
                ('carton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartones.Carton')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partidas.Partida')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
