# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impresion',
            old_name='linea',
            new_name='linea_1',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='ganador_10',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='ganador_6',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='ganador_7',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='ganador_8',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='ganador_9',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_10',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_6',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_7',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_8',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_9',
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_5',
            field=models.IntegerField(default=0),
        ),
    ]
