# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-28 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartones', '0002_auto_20171228_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impresion',
            name='posible_1',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_2',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_3',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_4',
        ),
        migrations.RemoveField(
            model_name='impresion',
            name='posible_5',
        ),
    ]
