# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartones', '0003_auto_20171228_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='numeroCarton',
            field=models.IntegerField(default=0),
        ),
    ]
