# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0003_sala_created_at'),
        ('cartones', '0006_remove_asignacion_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='salas.Sala'),
            preserve_default=False,
        ),
    ]
