# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartones', '0007_asignacion_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresion',
            name='ganador_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impresion',
            name='ganador_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='impresion',
            name='linea_7',
            field=models.IntegerField(default=0),
        ),
    ]
