# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bloqueado',
            field=models.CharField(default=b'no', max_length=2),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fallidos',
            field=models.IntegerField(default=0),
        ),
    ]
