# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('thumb', models.ImageField(default='pic_folder/no-image-thumb.png', upload_to='salas/logos/')),
            ],
        ),
    ]
