# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-01 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='activa',
            field=models.CharField(default='Si', max_length=2),
        ),
    ]
