# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-15 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salas', '0002_sala_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
